name: Coverage Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  codecov-backend:
    name: Codecov Backend
    runs-on: ubuntu-18.04

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev dependencies
        run: yarn workspace backend install

      - name: Create Databse
        run: sudo docker-compose -f backend/__tests__/docker-compose.test.yml -p testing up -d

      - name: Create env file
        run: |
          cd backend
          cat << EOF > .env
          DATABASE_URL=mongodb://localhost:27017/local?retryWrites=false
          EOF

      - name: Run the backend-tests
        run: yarn workspace backend run test
        # with:
        # NODE_ENV: 'test'
        # DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  codecov-frontend:
    name: Codecov Frontend
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dev dependencies
        run: yarn workspace frontend install

      - name: Run the frontend-tests
        run: yarn workspace frontend build:next && yarn workspace frontend e2e:headless

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
