name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn workspace frontend install    
    
    - name: Create env file
      run: |
          cd frontend
          cat << EOF > .env
          BASE_URL=${{ secrets.BASE_URL }}
          AUTHORIZATION=${{ secrets.AUTHORIZATION }}
          EOF

    - name: Build
      run: |
        yarn workspace frontend build:envs
        yarn workspace frontend build
        yarn workspace frontend zip
        
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@2.2.0
      with:
        file-path: chrome-extension.zip
        extension-id: 'hgeljhlpmkmbblgnnoalfgedcaekbcnd'
        client-id: ${{ secrets.CLIENT_ID }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
